# I will use this file to create the infrastructure for the project via Portainer on the server
# ---
version: "3"

volumes:
  pgdata:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  proxy:
    driver: bridge

services:
  website:
    image: lanzoninicola/clockdown-website:latest
    container_name: clockdown-website
    hostname: clockdown-website
    #restart: always
    #depends_on:
    #- postgres
    networks:
      - frontend
      - backend
    command: "npm start"
    working_dir: /myapp
    environment:
      - NODE_ENV=production
    # expose is a metadata, it has no effect on the container
    expose:
      - "3000"
    #ports:
    #  - "80:3000"

  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the
  # address of this container.
  postgres:
    container_name: clockdown-db
    image: postgres:14.1-alpine
    hostname: clockdown-db
    networks:
      - backend
    environment:
      # You can set the value of environment variables
      # in your docker-compose.yml file
      # Our Node app will use these to connect
      # to the database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    expose:
      - "5432"
    #ports:
    # Standard port for PostgreSQL databases
    # - "3254:5432"
    #   volumes:
    # When the PostgresSQL container is started it will run any scripts
    # provided in the `docker-entrypoint-initdb.d` directory, this connects
    # our seed file to that directory so that it gets run
    # - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    volumes:
      #- ./data:/data/db
      - pgdata:/var/lib/postgresql/data

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin:
    image: dpage/pgadmin4
    container_name: clockdown-pgadmin
    hostname: clockdown-pgadmin
    networks:
      - frontend
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    #ports:
    #  - "80:80"
    depends_on:
      - postgres

  traefik:
    image: lanzoninicola/traefik:latest
    container_name: "traefik"
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080" # Don't do this in production!
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
