version: "3"

volumes:
  pgdata:
    driver: local

services:
  website-editor:
    container_name: clockdown-website-editor
    # specifies the build configuration for creating container image from source (Dockerfile)
    build: ./website-editor
    hostname: clockdown-website-editor
    #restart: always
    depends_on:
      - rest-api
    command: "npm start"
    working_dir: /myapp
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3000:3000"

  rest-api:
    container_name: clockdown-rest-api
    build: ./rest-api
    hostname: clockdown-rest-api
    #restart: always
    depends_on:
      - postgres
    command: "npm run start"
    working_dir: /home/node/server
    environment:
      - NODE_ENV=production
    expose:
      - "5000"
    ports:
      - "5000:8090"

  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the
  # address of this container.
  postgres:
    container_name: clockdown-db
    image: postgres:14.1-alpine
    hostname: clockdown-db
    environment:
      # You can set the value of environment variables
      # in your docker-compose.yml file
      # Our Node app will use these to connect
      # to the database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      # Standard port for PostgreSQL databases
      - "3254:5432"
      #   volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      # - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    volumes:
      #- ./data:/data/db
      - pgdata:/var/lib/postgresql/data

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin:
    image: dpage/pgadmin4
    hostname: clockdown-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
