version: "3"
services:
  frontend:
    container_name: clockdown-remixrun
    # represent the docker image (./frontend/Dockerfile)
    build: frontend
    restart: always
    depends_on:
      - backend
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "5000"
    ports:
      - "5000:3000"

  backend:
    container_name: clockdown-backend
    build: backend
    restart: always
    depends_on:
      - postgres
    command: "npm run start"
    working_dir: /home/node/server
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3000:3000"

  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the
  # address of this container.
  postgres:
    container_name: clockdown-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      # You can set the value of environment variables
      # in your docker-compose.yml file
      # Our Node app will use these to connect
      # to the database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      # Standard port for PostgreSQL databases
      - "3254:5432"
      #   volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      # - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    volumes:
      #- ./data:/data/db
      - postgres-dbdata:/data/db

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
