version: "3"

volumes:
  local-pgdata:
    driver: local
  local-nginxdata:
    driver: local
  local-letsencrypt:
    driver: local

networks:
  flat:
    driver: bridge

services:
  website:
    container_name: local-clockdown-website
    # specifies the build configuration for creating container image from source (Dockerfile)
    build: ./website
    hostname: clockdown-website
    #restart: always
    depends_on:
      - postgres
    networks:
      - flat
    command: "npm start"
    working_dir: /myapp
    environment:
      - NODE_ENV=production
    # expose is a metadata, it has no effect on the container
    expose:
      - "3000"
    ports:
      - "3000:3000"

  # This is the configuration for our PostgreSQL database container
  # Note the `postgres` name is important, in out Node app when we refer
  # to  `host: "postgres"` that value is mapped on the network to the
  # address of this container.
  postgres:
    container_name: local-clockdown-db
    image: postgres:14.1-alpine
    hostname: clockdown-db
    networks:
      - flat
    environment:
      # You can set the value of environment variables
      # in your docker-compose.yml file
      # Our Node app will use these to connect
      # to the database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    expose:
      - "5432"
    ports:
      # Standard port for PostgreSQL databases
      - "3254:5432"
    #   volumes:
    # When the PostgresSQL container is started it will run any scripts
    # provided in the `docker-entrypoint-initdb.d` directory, this connects 
    # our seed file to that directory so that it gets run
    # - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    volumes:
      #- ./data:/data/db
      - local-pgdata:/var/lib/postgresql/data

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin:
    image: dpage/pgadmin4
    container_name: local-clockdown-pgadmin
    hostname: clockdown-pgadmin
    networks:
      - flat
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "8080:80"
    depends_on:
      - postgres

  nginx:
    image: "lanzoninicola/nginx-proxy-manager:1.1"
    container_name: local-clockdown-nginx
    hostname: clockdown-nginx
    restart: unless-stopped
    networks:
      - flat
    expose:
      - "443"
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
    # Uncomment this if you want to change the location of
    # the SQLite DB file within the container
    # DB_SQLITE_FILE: "/data/database.sqlite"

    # Uncomment this if IPv6 is not enabled on your host
    # DISABLE_IPV6: 'true'

    volumes:
      - local-nginxdata:/data
      - local-letsencrypt:/etc/letsencrypt
