import type { Typography } from "~/client/templates-editor/countdown-widget-typography/types";

const googleWebFonts: Typography[] = [
  { fontFamily: "Roboto", fontWeight: "400", pro: false },
  { fontFamily: "Open Sans", fontWeight: "400", pro: true },
  { fontFamily: "Montserrat", fontWeight: "400", pro: false },
  { fontFamily: "Lato", fontWeight: "400", pro: false },
  { fontFamily: "Poppins", fontWeight: "400", pro: false },
  { fontFamily: "Source Sans Pro", fontWeight: "400", pro: true },
  { fontFamily: "Roboto Condensed", fontWeight: "400", pro: true },
  { fontFamily: "Oswald", fontWeight: "400", pro: true },
  { fontFamily: "Raleway", fontWeight: "400", pro: true },
  { fontFamily: "Inter", fontWeight: "400", pro: false },
  { fontFamily: "Noto Sans", fontWeight: "400", pro: true },
  { fontFamily: "Ubuntu", fontWeight: "400", pro: true },
  { fontFamily: "Nunito Sans", fontWeight: "400", pro: true },
  { fontFamily: "Nunito", fontWeight: "400", pro: true },
  { fontFamily: "PT Sans", fontWeight: "400", pro: true },
  { fontFamily: "Rubik", fontWeight: "400", pro: true },
  { fontFamily: "Mukta", fontWeight: "400", pro: true },
  { fontFamily: "Noto Sans KR", fontWeight: "400", pro: true },
  { fontFamily: "Work Sans", fontWeight: "400", pro: true },
  { fontFamily: "Kanit", fontWeight: "400", pro: true },
  { fontFamily: "Fira Sans", fontWeight: "400", pro: true },
  { fontFamily: "Nanum Gothic", fontWeight: "400", pro: true },
  { fontFamily: "Noto Sans TC", fontWeight: "400", pro: true },
  { fontFamily: "Barlow", fontWeight: "400", pro: true },
  { fontFamily: "Roboto Mono", fontWeight: "400", pro: true },
  { fontFamily: "Inconsolata", fontWeight: "400", pro: true },
  { fontFamily: "Source Code Pro", fontWeight: "400", pro: true },
  { fontFamily: "IBM Plex Mono", fontWeight: "400", pro: true },
  { fontFamily: "Space Mono", fontWeight: "400", pro: true },
  { fontFamily: "PT Mono", fontWeight: "400", pro: true },
  { fontFamily: "Ubuntu Mono", fontWeight: "400", pro: true },
  { fontFamily: "Nanum Gothic Coding", fontWeight: "400", pro: true },
  { fontFamily: "Cousine", fontWeight: "400", pro: true },
  { fontFamily: "Share Tech Mono", fontWeight: "400", pro: true },
  { fontFamily: "Fira Mono", fontWeight: "400", pro: true },
  { fontFamily: "Courier Prime", fontWeight: "400", pro: true },
  { fontFamily: "VT323", fontWeight: "400", pro: true },
  { fontFamily: "Anonymous Pro", fontWeight: "400", pro: true },
  { fontFamily: "Fira Code", fontWeight: "400", pro: true },
  { fontFamily: "Cutive Mono", fontWeight: "400", pro: true },
  { fontFamily: "JetBrains Mono", fontWeight: "400", pro: true },
  { fontFamily: "Overpass Mono", fontWeight: "400", pro: true },
  { fontFamily: "DM Mono", fontWeight: "400", pro: true },
  { fontFamily: "Noto Sans Mono", fontWeight: "400", pro: true },
  { fontFamily: "Oxygen Mono", fontWeight: "400", pro: true },
  { fontFamily: "Nova Mono", fontWeight: "400", pro: true },
  { fontFamily: "Azeret Mono", fontWeight: "400", pro: true },
  { fontFamily: "Major Mono Display", fontWeight: "400", pro: true },
  { fontFamily: "B612 Mono", fontWeight: "400", pro: true },
  { fontFamily: "Roboto Slab", fontWeight: "400", pro: false },
  { fontFamily: "Playfair Display", fontWeight: "400", pro: false },
  { fontFamily: "Merriweather", fontWeight: "400", pro: false },
  { fontFamily: "Lora", fontWeight: "400", pro: false },
  { fontFamily: "PT Serif", fontWeight: "400", pro: true },
  { fontFamily: "Noto Serif", fontWeight: "400", pro: true },
  { fontFamily: "Libre Baskerville", fontWeight: "400", pro: true },
  { fontFamily: "Bitter", fontWeight: "400", pro: true },
  { fontFamily: "Source Serif Pro", fontWeight: "400", pro: true },
  { fontFamily: "EB Garamond", fontWeight: "400", pro: true },
  { fontFamily: "Crimson Text", fontWeight: "400", pro: true },
  { fontFamily: "Arvo", fontWeight: "400", pro: true },
  { fontFamily: "Noto Serif JP", fontWeight: "400", pro: true },
  { fontFamily: "Slabo 27px", fontWeight: "400", pro: true },
  { fontFamily: "Cormorant Garamond", fontWeight: "400", pro: true },
  { fontFamily: "IBM Plex Serif", fontWeight: "400", pro: true },
  { fontFamily: "Zilla Slab", fontWeight: "400", pro: true },
  { fontFamily: "Nanum Myeongjo", fontWeight: "400", pro: true },
  { fontFamily: "Bree Serif", fontWeight: "400", pro: true },
  { fontFamily: "Domine", fontWeight: "400", pro: true },
  { fontFamily: "Vollkorn", fontWeight: "400", pro: true },
  { fontFamily: "Cinzel", fontWeight: "400", pro: true },
  { fontFamily: "DM Serif Display", fontWeight: "400", pro: true },
  { fontFamily: "Tinos", fontWeight: "400", pro: true },
  { fontFamily: "Frank Ruhl Libre", fontWeight: "400", pro: true },
  { fontFamily: "Bebas Neue", fontWeight: "400", pro: true },
  { fontFamily: "Lobster", fontWeight: "400", pro: false },
  { fontFamily: "Comfortaa", fontWeight: "400", pro: true },
  { fontFamily: "Abril Fatface", fontWeight: "400", pro: false },
  { fontFamily: "Fredoka One", fontWeight: "400", pro: true },
  { fontFamily: "Alfa Slab One", fontWeight: "400", pro: false },
  { fontFamily: "Righteous", fontWeight: "400", pro: true },
  { fontFamily: "Patua One", fontWeight: "400", pro: true },
  { fontFamily: "Lobster Two", fontWeight: "400", pro: true },
  { fontFamily: "Baloo 2", fontWeight: "400", pro: true },
  { fontFamily: "Passion One", fontWeight: "400", pro: true },
  { fontFamily: "Press Start 2P", fontWeight: "400", pro: true },
  { fontFamily: "Titan One", fontWeight: "400", pro: true },
  { fontFamily: "Concert One", fontWeight: "400", pro: true },
  { fontFamily: "Staatliches", fontWeight: "400", pro: true },
  { fontFamily: "Luckiest Guy", fontWeight: "400", pro: true },
  { fontFamily: "Bangers", fontWeight: "400", pro: true },
  { fontFamily: "Macondo", fontWeight: "400", pro: true },
  { fontFamily: "Creepster", fontWeight: "400", pro: true },
  { fontFamily: "Yeseva One", fontWeight: "400", pro: true },
  { fontFamily: "Carter One", fontWeight: "400", pro: true },
  { fontFamily: "Poiret One", fontWeight: "400", pro: true },
  { fontFamily: "Special Elite", fontWeight: "400", pro: true },
  { fontFamily: "Lilita One", fontWeight: "400", pro: true },
  { fontFamily: "Fugaz One", fontWeight: "400", pro: true },
  { fontFamily: "Dancing Script", fontWeight: "400", pro: true },
  { fontFamily: "Pacifico", fontWeight: "400", pro: true },
  { fontFamily: "Shadows Into Light", fontWeight: "400", pro: true },
  { fontFamily: "Caveat", fontWeight: "400", pro: true },
  { fontFamily: "Satisfy", fontWeight: "400", pro: true },
  { fontFamily: "Indie Flower", fontWeight: "400", pro: true },
  { fontFamily: "Permanent Marker", fontWeight: "400", pro: true },
  { fontFamily: "Amatic SC", fontWeight: "400", pro: true },
  { fontFamily: "Covered By Your Grace", fontWeight: "400", pro: true },
  { fontFamily: "Kalam", fontWeight: "400", pro: true },
  { fontFamily: "Courgette", fontWeight: "400", pro: true },
  { fontFamily: "Great Vibes", fontWeight: "400", pro: true },
  { fontFamily: "La Belle Aurore", fontWeight: "400", pro: true },
  { fontFamily: "Kaushan Script", fontWeight: "400", pro: true },
  { fontFamily: "Cookie", fontWeight: "400", pro: true },
  { fontFamily: "Patrick Hand", fontWeight: "400", pro: true },
  { fontFamily: "Gloria Hallelujah", fontWeight: "400", pro: true },
  { fontFamily: "Yellowtail", fontWeight: "400", pro: true },
  { fontFamily: "Sacramento", fontWeight: "400", pro: true },
  { fontFamily: "Neucha", fontWeight: "400", pro: true },
  { fontFamily: "Handlee", fontWeight: "400", pro: true },
  { fontFamily: "Architects Daughter", fontWeight: "400", pro: true },
  { fontFamily: "Marck Script", fontWeight: "400", pro: true },
  { fontFamily: "Parisienne", fontWeight: "400", pro: true },
  { fontFamily: "Merienda", fontWeight: "400", pro: true },
];

export default googleWebFonts;
