import type { Templates } from "../types";

export const TEMPLATES_BASE_ASSET_PATH =
  "/src/editor/editor-properties/properties/templates-properties-group/assets/";

export const TEMPLATES: Templates = {
  // default: {
  //   id: "default",
  //   name: "Default",
  //   editable: true,
  //   disabled: false,
  //   style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:Inter}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;width:max-content;background:#fff}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-container]{display:flex;justify-content:center}div[data-element=countdown-wrapper]{-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;padding:.5rem 0;width:100%;max-width:978px}h2[data-element=countdown-title]{max-width:370px;text-align:center}}`,
  //   image: "default",
  //   fontFamily: "Inter",
  //
  // },
  orangi: {
    id: "orangi",
    name: "Orangi",
    editable: true,
    disabled: false,
    image: "orangi",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#F4803E",
        css: null,
        height: 1,
      },
      title: {
        fontFamily: "Oswald",
        fontWeight: "700",
        fontSize: {
          lg: 20,
          sm: 16,
        },
        fontColor: null,
        titleTextTransform: "uppercase",
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: false,
        unitNumberFontFamily: "Oswald",
        unitNumberFontWeight: "700",
        unitNumberFontSize: {
          lg: 30,
          sm: 37,
          md: 31,
        },
        unitNumberFontColor: null,
        lastUnitColor: null,
        unitLabelFontFamily: "Oswald",
        unitLabelFontWeight: "400",
        unitLabelFontSize: {
          lg: 15,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: null,
        unitLabelTextTransform: "lowercase",
      },
    },
  },
  disco: {
    id: "disco",
    name: "Disco",
    editable: true,
    disabled: false,
    image: "disco",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#f2f2f2",
        css: null,
        borderRadius: 10,
        borderColor: "#C10B99",
        borderWidth: 3,
        reverseOrderItems: true,
        height: 1,
      },
      title: {
        fontFamily: "Oswald",
        fontWeight: "400",
        fontSize: {
          lg: 19,
        },
        fontColor: null,
        titleTextTransform: "uppercase",
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: false,
        unitNumberFontFamily: "Monoton",
        unitNumberFontWeight: "400",
        unitNumberFontSize: {
          lg: 30,
          sm: 33,
          md: 31,
        },
        unitNumberFontColor: null,
        lastUnitColor: "#C10B99",
        unitLabelFontFamily: "Monoton",
        unitLabelFontWeight: "400",
        unitLabelFontSize: {
          lg: 15,
          sm: 12,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: null,
        unitLabelTextTransform: "uppercase",
      },
    },
  },

  lanche: {
    id: "lanche",
    name: "Lanche",
    editable: true,
    disabled: false,
    image: "lanche",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#EA0D0D",
        css: null,
        reverseOrderItems: true,
        height: 1,
      },
      title: {
        fontFamily: "Kanit",
        fontWeight: "400",
        fontSize: {
          lg: 19,
        },
        fontColor: null,
        titleTextTransform: "uppercase",
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: false,
        unitNumberFontFamily: "Kanit",
        unitNumberFontWeight: "700",
        unitNumberFontSize: {
          lg: 30,
          sm: 33,
          md: 31,
        },
        unitNumberFontColor: "#FFEF60",
        lastUnitColor: "#1B1B1B",
        unitLabelFontFamily: "Kanit",
        unitLabelFontWeight: "700",
        unitLabelFontSize: {
          lg: 15,
          sm: 12,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#FFEF60",
        unitLabelTextTransform: "uppercase",
      },
    },
  },

  oldSkool: {
    id: "oldSkool",
    name: "Oldkool",
    editable: true,
    disabled: false,
    image: "oldskool",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#D9D9D9",
        css: null,
        reverseOrderItems: true,
        height: 1,
        borderRadius: 10,
      },
      title: {
        fontFamily: "Inter",
        fontWeight: "700",
        fontSize: {
          lg: 16,
          sm: 14,
        },
        fontColor: null,
      },
      timer: {
        showSeparator: false,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: false,
        unitNumberFontFamily: "Monofett",
        unitNumberFontWeight: "400",
        unitNumberFontSize: {
          lg: 48,
          sm: 62,
          md: 31,
        },
        unitNumberFontColor: "#1b1b1b",
        lastUnitColor: "#A39D00",
        unitLabelFontFamily: "Inter",
        unitLabelFontWeight: "700",
        unitLabelFontSize: {
          lg: 15,
          sm: 12,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#1b1b1b",
        unitLabelTextTransform: "lowercase",
      },
    },
  },

  perfume: {
    id: "perfume",
    name: "Perfume",
    editable: true,
    disabled: false,
    image: "perfume",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#FCDEE3",
        css: null,
        reverseOrderItems: true,
        height: 1,
        borderRadius: 0,
        borderWidth: 0,
      },
      title: {
        fontFamily: "Abril Fatface",
        fontWeight: "400",
        fontSize: {
          lg: 16,
          sm: 15,
        },
        fontColor: null,
      },
      timer: {
        showSeparator: false,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: true,
        unitNumberFontFamily: "Abril Fatface",
        unitNumberFontWeight: "400",
        unitNumberFontSize: {
          lg: 33,
          sm: 50,
          md: 31,
        },
        unitNumberFontColor: "#1b1b1b",
        lastUnitColor: "#930A8E",
        unitLabelFontFamily: "Abril Fatface",
        unitLabelFontWeight: "700",
        unitLabelFontSize: {
          lg: 15,
          sm: 16,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#1b1b1b",
        unitLabelTextTransform: "lowercase",
      },
    },
  },

  smart: {
    id: "smart",
    name: "Smart",
    editable: true,
    disabled: false,
    image: "smart",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#FFFFFF",
        css: null,
        reverseOrderItems: true,
        height: 1,
        borderRadius: 0,
        borderWidth: 0,
      },
      title: {
        fontFamily: "Anton",
        fontWeight: "400",
        fontSize: {
          lg: 20,
          sm: 17,
        },
        fontColor: null,
      },
      timer: {
        showSeparator: false,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: true,
        unitNumberFontFamily: "Anton",
        unitNumberFontWeight: "400",
        unitNumberFontSize: {
          lg: 33,
          sm: 50,
          md: 31,
        },
        unitNumberFontColor: "#1b1b1b",
        lastUnitColor: "#828282",
        unitLabelFontFamily: "Anton",
        unitLabelFontWeight: "700",
        unitLabelFontSize: {
          lg: 15,
          sm: 16,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#1b1b1b",
        unitLabelTextTransform: "lowercase",
      },
    },
  },

  space: {
    id: "space",
    name: "Space",
    editable: true,
    disabled: false,
    image: "space",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#506C87",
        css: null,
        reverseOrderItems: true,
        height: 1,
        borderRadius: 0,
        borderWidth: 0,
      },
      title: {
        fontFamily: "Space Mono",
        fontWeight: "400",
        fontSize: {
          lg: 20,
          sm: 15,
        },
        fontColor: "#ffffff",
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: true,
        unitNumberFontFamily: "Space Mono",
        unitNumberFontWeight: "700",
        unitNumberFontSize: {
          lg: 33,
          sm: 32,
          md: 31,
        },
        unitNumberFontColor: "#ffffff",
        lastUnitColor: "#EA3C2E",
        unitLabelFontFamily: "Space Mono",
        unitLabelFontWeight: "700",
        unitLabelFontSize: {
          lg: 15,
          sm: 13,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#ffffff",
        unitLabelTextTransform: "lowercase",
      },
    },
  },
  monospace: {
    id: "monospace",
    name: "Monospace",
    editable: true,
    disabled: false,
    image: "monospace",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#C10B99",
        css: null,
        reverseOrderItems: false,
        height: 1,
        borderRadius: 0,
        borderWidth: 0,
      },
      title: {
        fontFamily: "Roboto Mono",
        fontWeight: "400",
        fontSize: {
          lg: 20,
          sm: 16,
        },
        fontColor: "#ffffff",
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: true,
        unitNumberFontFamily: "Roboto Mono",
        unitNumberFontWeight: "700",
        unitNumberFontSize: {
          lg: 33,
          sm: 32,
          md: 31,
        },
        unitNumberFontColor: "#ffffff",
        lastUnitColor: "#000000",
        unitLabelFontFamily: "Roboto Mono",
        unitLabelFontWeight: "700",
        unitLabelFontSize: {
          lg: 15,
          sm: 13,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#ffffff",
        unitLabelTextTransform: "lowercase",
      },
    },
  },

  greeny: {
    id: "greeny",
    name: "Greeny",
    editable: true,
    disabled: false,
    image: "greeny",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#73f8ba",
        css: null,
        reverseOrderItems: false,
        height: 1,
        borderRadius: 0,
        borderWidth: 0,
      },
      title: {
        fontFamily: "Oswald",
        fontWeight: "700",
        fontSize: {
          lg: 20,
          sm: 18,
        },
        fontColor: "#1b1b1b",
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: true,
        unitNumberFontFamily: "Oswald",
        unitNumberFontWeight: "700",
        unitNumberFontSize: {
          lg: 33,
          sm: 32,
          md: 31,
        },
        unitNumberFontColor: "#000000",
        lastUnitColor: "#51723b",
        unitLabelFontFamily: "Oswald",
        unitLabelFontWeight: "700",
        unitLabelFontSize: {
          lg: 15,
          sm: 13,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#000000",
        unitLabelTextTransform: "lowercase",
      },
    },
  },
  spicy: {
    id: "spicy",
    name: "Spicy",
    editable: true,
    disabled: false,
    image: "spicy",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#f7d3b8",
        css: null,
        reverseOrderItems: false,
        height: 1,
        borderRadius: 0,
        borderWidth: 0,
      },
      title: {
        fontFamily: "Bungee Spice",
        fontWeight: "400",
        fontSize: {
          lg: 20,
          sm: 18,
        },
        fontColor: "#1b1b1b",
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: true,
        unitNumberFontFamily: "Bungee Spice",
        unitNumberFontWeight: "400",
        unitNumberFontSize: {
          lg: 33,
          sm: 32,
          md: 31,
        },
        unitNumberFontColor: "#000000",
        lastUnitColor: "#000000",
        unitLabelFontFamily: "Bungee Spice",
        unitLabelFontWeight: "400",
        unitLabelFontSize: {
          lg: 15,
          sm: 13,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: "#000000",
        unitLabelTextTransform: "lowercase",
      },
    },
  },
};
