import { Templates } from "../types";

export const TEMPLATES_BASE_ASSET_PATH =
  "/src/editor/editor-properties/properties/templates-properties-group/assets/";

export const TEMPLATES: Templates = {
  // default: {
  //   id: "default",
  //   name: "Default",
  //   editable: true,
  //   disabled: false,
  //   style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:Inter}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;width:max-content;background:#fff}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-container]{display:flex;justify-content:center}div[data-element=countdown-wrapper]{-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;padding:.5rem 0;width:100%;max-width:978px}h2[data-element=countdown-title]{max-width:370px;text-align:center}}`,
  //   image: "default",
  //   fontFamily: "Inter",
  //
  // },
  orangi: {
    id: "orangi",
    name: "Orangi",
    editable: true,
    disabled: false,
    image: "orangi",
    fontFamily: "Oswald",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#F4803E",
        css: null,
      },
      title: {
        fontFamily: "Oswald",
        fontWeight: "700",
        fontSize: {
          lg: 20,
          sm: 16,
        },
        fontColor: null,
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: false,
        unitNumberFontFamily: "Oswald",
        unitNumberFontWeight: "700",
        unitNumberFontSize: {
          lg: 30,
          sm: 37,
          md: 31,
        },
        unitNumberFontColor: null,
        lastUnitColor: null,
        unitLabelFontFamily: "Oswald",
        unitLabelFontWeight: "400",
        unitLabelFontSize: {
          lg: 15,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: null,
        unitLabelTextTransform: "lowercase",
      },
    },
  },
  disco: {
    id: "disco",
    name: "Disco",
    editable: true,
    disabled: false,
    image: "disco",
    fontFamily: "Monoton",
    theme: {
      layout: {
        orientation: "auto",
        gap: 1,
        transparentBackground: false,
        backgroundColor: "#f2f2f2",
        css: null,
        borderRadius: 10,
        borderColor: "#C10B99",
        borderWidth: 3,
        reverseOrderItems: true,
        height: 1,
      },
      title: {
        fontFamily: "Oswald",
        fontWeight: "400",
        fontSize: {
          lg: 19,
        },
        fontColor: null,
      },
      timer: {
        showSeparator: true,
        separatorChar: ":",
        hideDays: false,
        hideHours: false,
        hideSeconds: false,
        padWithZero: false,
        unitNumberFontFamily: "Monoton",
        unitNumberFontWeight: "400",
        unitNumberFontSize: {
          lg: 30,
          sm: 33,
          md: 31,
        },
        unitNumberFontColor: null,
        lastUnitColor: "#C10B99",
        unitLabelFontFamily: "Monoton",
        unitLabelFontWeight: "400",
        unitLabelFontSize: {
          lg: 15,
          sm: 12,
        },
        unitLabelLanguage: "en-US",
        unitLabelFontColor: null,
        unitLabelTextTransform: "uppercase",
      },
    },
  },

  lanche: {
    id: "lanche",
    name: "Lanche",
    editable: true,
    disabled: false,
    style: `h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:100%;font-weight:600;font-family:Oswald,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:grid;justify-items:center;gap:.75rem;margin:auto;padding:1rem .5rem;background:#f4803e}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;text-transform:uppercase}div[data-element=countdown-units]{display:grid;grid-template-columns:repeat(7,1fr);column-gap:.5rem;width:min-content}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}div[data-element=countdown-unit]:not(div[data-element=countdown-unit][data-unit-type=separator]){min-width:70px}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:150%}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:75%;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-wrapper]{grid-template-columns:repeat(2,1fr)}h2[data-element=countdown-title]{width:50ch;text-align:left}}`,
    image: "lanche",
    fontFamily: "Kanit",
  },

  mopi: {
    id: "mopi",
    name: "Mopi",
    editable: true,
    disabled: false,
    style: `h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:100%;font-weight:600;font-family:Oswald,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:grid;justify-items:center;gap:.75rem;margin:auto;padding:1rem .5rem;background:#f4803e}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;text-transform:uppercase}div[data-element=countdown-units]{display:grid;grid-template-columns:repeat(7,1fr);column-gap:.5rem;width:min-content}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}div[data-element=countdown-unit]:not(div[data-element=countdown-unit][data-unit-type=separator]){min-width:70px}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:150%}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:75%;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-wrapper]{grid-template-columns:repeat(2,1fr)}h2[data-element=countdown-title]{width:50ch;text-align:left}}`,
    image: "mopi",
    fontFamily: "Outfit",
  },

  oldSkool: {
    id: "oldSkool",
    name: "Oldkool",
    editable: true,
    disabled: false,
    style: `h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:100%;font-weight:600;font-family:Oswald,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:grid;justify-items:center;gap:.75rem;margin:auto;padding:1rem .5rem;background:#f4803e}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;text-transform:uppercase}div[data-element=countdown-units]{display:grid;grid-template-columns:repeat(7,1fr);column-gap:.5rem;width:min-content}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}div[data-element=countdown-unit]:not(div[data-element=countdown-unit][data-unit-type=separator]){min-width:70px}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:150%}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:75%;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-wrapper]{grid-template-columns:repeat(2,1fr)}h2[data-element=countdown-title]{width:50ch;text-align:left}}`,
    image: "oldskool",
    fontFamily: "Monofett",
  },

  perfume: {
    id: "perfume",
    name: "Perfume",
    editable: true,
    disabled: false,
    style: `h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:100%;font-weight:600;font-family:Oswald,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:grid;justify-items:center;gap:.75rem;margin:auto;padding:1rem .5rem;background:#f4803e}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;text-transform:uppercase}div[data-element=countdown-units]{display:grid;grid-template-columns:repeat(7,1fr);column-gap:.5rem;width:min-content}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}div[data-element=countdown-unit]:not(div[data-element=countdown-unit][data-unit-type=separator]){min-width:70px}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:150%}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:75%;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-wrapper]{grid-template-columns:repeat(2,1fr)}h2[data-element=countdown-title]{width:50ch;text-align:left}}`,
    image: "perfume",
    fontFamily: "Abril Fatface",
  },

  smart: {
    id: "smart",
    name: "Smart",
    editable: true,
    disabled: false,
    style: `h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:100%;font-weight:600;font-family:Oswald,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:grid;justify-items:center;gap:.75rem;margin:auto;padding:1rem .5rem;background:#f4803e}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;text-transform:uppercase}div[data-element=countdown-units]{display:grid;grid-template-columns:repeat(7,1fr);column-gap:.5rem;width:min-content}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}div[data-element=countdown-unit]:not(div[data-element=countdown-unit][data-unit-type=separator]){min-width:70px}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:150%}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:75%;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-wrapper]{grid-template-columns:repeat(2,1fr)}h2[data-element=countdown-title]{width:50ch;text-align:left}}`,
    image: "smart",
    fontFamily: "Anton",
  },

  tech: {
    id: "space",
    name: "Space",
    editable: true,
    disabled: false,
    style: `h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:100%;font-weight:600;font-family:Oswald,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:grid;justify-items:center;gap:.75rem;margin:auto;padding:1rem .5rem;background:#f4803e}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;text-transform:uppercase}div[data-element=countdown-units]{display:grid;grid-template-columns:repeat(7,1fr);column-gap:.5rem;width:min-content}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}div[data-element=countdown-unit]:not(div[data-element=countdown-unit][data-unit-type=separator]){min-width:70px}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:150%}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:75%;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}@media (min-width:768px){div[data-element=countdown-wrapper]{grid-template-columns:repeat(2,1fr)}h2[data-element=countdown-title]{width:50ch;text-align:left}}`,
    image: "space",
    fontFamily: "Space Mono",
  },
  monospace: {
    id: "monospace",
    name: "Monospace",
    editable: true,
    disabled: false,
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:1rem;font-weight:400;font-family:monospace}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:370px;display:flex;align-items:center;justify-content:center;padding-inline:1rem;background-color:#8a2be2}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;padding:1rem .5rem;width:100%;gap:2rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;color:#fff;font-weight:700}div[data-element=countdown-units]{display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;width:100%;-webkit-justify-content:center;justify-content:center;font-weight:700;gap:.5rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem;width:80px}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;color:#000;background-color:#fff;width:100%;text-align:center;padding-block:1rem;border-radius:5px}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.75rem;letter-spacing:1px;color:#fff;text-transform:uppercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed;display:none}@media (min-width:768px){div[data-element=countdown-container]{width:100vw;display:flex;justify-content:center;background-size:contain;background-repeat:no-repeat;background-position:center}div[data-element=countdown-wrapper]{margin-inline:20%;padding:.5rem 0;margin-top:inherit;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-ms-flex-wrap:nowrap;flex-wrap:nowrap;gap:1rem}h2[data-element=countdown-title]{max-width:50%;text-align:left;line-height:1.1}div[data-element=countdown-units]{max-width:50%}}@media (min-width:1440px){div[data-element=countdown-wrapper]{margin-inline:15%;gap:2rem}span[data-element=countdown-unit-number]{padding-block:0.5rem}}`,
    image: "monospace",
  },

  greeny: {
    id: "greeny",
    name: "Greeny",
    editable: true,
    disabled: false,
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:1rem;font-weight:700;font-family:Oswald,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:370px;display:flex;align-items:center;justify-content:center;padding-inline:1rem;background-color:#73f8ba}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;padding:1rem;width:100%;gap:1.5rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;font-weight:700;text-transform:uppercase}div[data-element=countdown-units]{display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;width:100%;-webkit-justify-content:center;justify-content:center;font-weight:700;gap:.5rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem;color:#000}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;width:100%;text-align:center;border-radius:5px}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.75rem;letter-spacing:1px;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed;grid-area:separator}@media (min-width:768px){div[data-element=countdown-container]{width:100vw;display:flex;justify-content:center;background-size:contain;background-repeat:no-repeat;background-position:center}div[data-element=countdown-wrapper]{margin-inline:20%;padding:.5rem 0;margin-top:inherit;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-ms-flex-wrap:nowrap;flex-wrap:nowrap;gap:1rem}h2[data-element=countdown-title]{max-width:50%;text-align:left;line-height:1.1}div[data-element=countdown-units]{max-width:50%}}@media (min-width:1440px){div[data-element=countdown-wrapper]{margin-inline:15%;gap:2rem}}`,
    image: "greeny",
    fontFamily: "Oswald",
  },
  spicy: {
    id: "spicy",
    name: "Spicy",
    editable: true,
    disabled: false,
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:1rem;font-weight:700;font-family:"Bungee Spice",sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:370px;display:flex;align-items:center;justify-content:center;padding-inline:1rem;background-color:#f7ebe8}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;padding:1rem;width:100%;gap:1.5rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;font-weight:700;text-transform:uppercase}div[data-element=countdown-units]{display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;width:100%;-webkit-justify-content:center;justify-content:center;font-weight:700;gap:.5rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem;color:#000}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;width:100%;text-align:center;border-radius:5px}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.75rem;letter-spacing:1px;text-transform:lowercase}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed;grid-area:separator}@media (min-width:768px){div[data-element=countdown-container]{width:100vw;display:flex;justify-content:center;background-size:contain;background-repeat:no-repeat;background-position:center}div[data-element=countdown-wrapper]{margin-inline:20%;padding:.5rem 0;margin-top:inherit;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;-ms-flex-wrap:nowrap;flex-wrap:nowrap;gap:1rem}h2[data-element=countdown-title]{max-width:50%;text-align:left;line-height:1.1}div[data-element=countdown-units]{max-width:50%}}@media (min-width:1440px){div[data-element=countdown-wrapper]{margin-inline:15%;gap:2rem}}`,
    image: "spicy",
    fontFamily: "Bungee Spice",
  },
};
